name: bovine viral diarrhea eradication data wrangling

on: 
  push:
    paths:
      - "ogd/bovine_viral_diarrhea_eradication/Daten für Dashboard.csv"  # Only trigger when CSV files are pushed to ogd/BVD_Ausrottung
  workflow_dispatch:

jobs:
  data-preparation:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Specify the Python version

      - name: Install Python packages
        run: |
          pip install -r system_0jE912Msrzr37POAg9/bovine_viral_diarrhea_eradication_requirements.txt
          
      - name: Run data preparation script
        run: python system_0jE912Msrzr37POAg9/bovine_viral_diarrhea_eradication_data_preparation.py

      - name: Remove input CSV file
        run: rm "ogd/bovine_viral_diarrhea_eradication/Daten für Dashboard.csv"

      - name: Commit result files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "bovine viral diarrhea eradication data wrangling" --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
