name: Foot rot control program Frictionless Validation

on:
  push:
    paths:
      - "ogd/foot_rot_control_program/eradication-foot-rot.csv"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Frictionless
        run: |
          python -m pip install frictionless

      - name: Validate CSV file with JSON schema
        run: |
          frictionless validate ogd/foot_rot_control_program/foot_rot_control_program.json