name: avian influenza frictionless validation

on:
  push:
    branches:
      - main
    paths:
      - 'ogd/monitoring_wild_birds_avian_influenza/**'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Frictionless
        run: |
          python -m pip install frictionless

      - name: Validate CSV file with JSON schema
        run: |
          frictionless validate ogd/monitoring_wild_birds_avian_influenza/monitoring_wild_birds_avian_influenza.json
