name: BVD Ampel Data Preparation

on: 
  push:
    paths:
      - "ogd/BVD_Ausrottung/BVD.csv"  # Only trigger when CSV files are pushed to ogd/BVD_Ausrottung

jobs:
  data-preparation:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # Specify the Python version

      - name: Install Python packages
        run: |
          pip install -r system_0jE912Msrzr37POAg9/TGTS_BVD_Ampel_requirements.txt
          
      - name: Run data preparation script
        run: python system_0jE912Msrzr37POAg9/TGTS_BVD_Ampel_data_preparation.py

      - name: Remove input CSV file
        run: rm "ogd/BVD_Ausrottung/BVD.csv"

      - name: Commit result files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Updated data after processing in BVD Ampel data preparation" --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
